pipeline {

    agent any

    environment {

        IMAGE_NAME = "jagdishbutte/lifestyle-ai-backend"
        CONTAINER_NAME = "lifestyle-ai-backend"

        DB_URL = credentials('db-url')
        DB_USERNAME = credentials('db-username')
        DB_PASSWORD = credentials('db-password')

        JWT_SECRET = credentials('jwt-secret')

        SERVER_PORT = "8080"
        SHOW_SQL = "false"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:latest .'
            }
        }

        stage('Push Image') {

            steps {

                withDockerRegistry(
                        credentialsId: 'dockerhub-credentials',
                        url: '') {

                    sh 'docker push $IMAGE_NAME:latest'
                }
            }
        }

        stage('Deploy to EC2') {

            steps {

                sshagent(credentials: ['ec2-ssh']) {

                    sh """

                    ssh -o StrictHostKeyChecking=no ubuntu@YOUR_EC2_IP << EOF

                    docker pull $IMAGE_NAME:latest

                    docker stop $CONTAINER_NAME || true

                    docker rm $CONTAINER_NAME || true

                    docker run -d \
                        --name $CONTAINER_NAME \
                        -p 8080:8080 \
                        -e DB_URL="$DB_URL" \
                        -e DB_USERNAME="$DB_USERNAME" \
                        -e DB_PASSWORD="$DB_PASSWORD" \
                        -e JWT_SECRET="$JWT_SECRET" \
                        -e SHOW_SQL=false \
                        -e SERVER_PORT=8080 \
                        $IMAGE_NAME:latest

                    docker image prune -f

                    EOF
                    """
                }
            }
        }
    }

    post {

        success {
            echo 'Deployment Successful 🚀'
        }

        failure {
            echo 'Deployment Failed ❌'
        }
    }
}