pipeline {

    agent any

    environment {
        IMAGE_NAME = "jagdishbutte/lifestyle-ai"
        IMAGE_TAG = "latest"
        CONTAINER_NAME = "lifestyle-ai-backend"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Debug Java') {
            steps {
                sh '''
                echo "===== WHOAMI ====="
                whoami
    
                echo "===== PATH ====="
                echo $PATH
    
                echo "===== JAVA_HOME ====="
                echo $JAVA_HOME
    
                echo "===== WHICH JAVA ====="
                which java
    
                echo "===== JAVA ====="
                java -version
    
                echo "===== WHICH MVN ====="
                which mvn
    
                echo "===== MAVEN ====="
                mvn -version
    
                env | sort
                '''
            }
        }

        stage('Build Jar') {
            steps {
                dir('backend') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'DockerHubCreds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {

                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {

                withCredentials([
                    file(credentialsId: 'backend-env', variable: 'ENV_FILE')
                ]) {

                    sh '''
                        docker pull ${IMAGE_NAME}:${IMAGE_TAG}

                        docker stop ${CONTAINER_NAME} || true
                        docker rm ${CONTAINER_NAME} || true

                        docker run -d \
                          --name ${CONTAINER_NAME} \
                          --restart unless-stopped \
                          --env-file "$ENV_FILE" \
                          -p 8080:8080 \
                          ${IMAGE_NAME}:${IMAGE_TAG}
                    '''
                }
            }
        }
    }

    post {

        success {
            echo "Deployment Successful ✅"
        }

        failure {
            echo "Deployment Failed ❌"
        }
    }
}